### PR TITLE
Prevent global require from being overridden.

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
I am just circling back on the global require pollution issue.

Here is my scenario:
1.  I have a webpacked module which contains a dgrid.  It is packaged as a UMD package.
2.  This UMD package gets dynamically loaded by a third party app (which happens to be using RequireJS with its own configuration).
3.  Once loaded the dojo require merrily replaces the existing require...

**Comment by chuckdumont** [comment]
Hi Gordon.  I don't want to change the behavior of the plugin with regard to global require.  Dojo defines global require, and applications that rely on this will break.

However, you should be able to accomplish what you desire by implementing the plugin described [here](https://github.com/OpenNTF/dojo-webpack-plugin/pull/92#issuecomment-350770800).

**Comment by GordonSmith** [comment]
That works thx.

**Comment by chuckdumont** [comment]
@GordonSmith, FYI, the ScopedRequirePlugin is now part of dojo-webpack-plugin.  See the [readme](https://github.com/OpenNTF/dojo-webpack-plugin#the-global-require-function).

**Comment by GordonSmith** [comment]
I shall check it out, next tine I upgrade - thx.

**Pull request closed without merging**
