### PR TITLE
Handle case where another AMD loader (e.g. requirejs) is already loaded.

### PR DESCRIPTION
**Pull request by chuckdumont**

### CODE REVIEW

**Comment by GordonSmith** [comment]
@chuckdumont here is another use case you should test for:
```
var reqOne = require.config({
    context: "version1",
    baseUrl: './'
});

reqOne (["./dist/index"], function (dgridShim) {
    console.log(dgridShim.BUILD_VERSION);
});
```

**Comment by chuckdumont** [comment]
@GordonSmith - The use case you present isn't supported.  Dynamically modifying a config at runtime is not something that webpack supports, so dojo-webpack-plugin can't do it either.  Note that webpack is loading the modules here, not Dojo.  In fact, the module loading machinery in dojo.js is disabled by has conditions and optimized out.   Only the code for resolving module names is retained.  Since webpack maps module names to bundled module ids at build time, changing the mappings, or adding new mappings, at runtime is something that cannot be done.

**Comment by GordonSmith** [comment]
That test was intended to be used from the consumer side, I wasn't implying that you should support it inside dojo code!

**Comment by chuckdumont** [comment]
I guess I need more context then.  require.config() is an AMD feature that allows client code to dynamically update the loader config at runtime for the subsequent loading of modules.  Translating that to webpack, it would be like trying to update webpack.config.js at runtime to affect the subsequent loading of modules by webpack.  It's just not something that is supported.

**Comment by chuckdumont** [comment]
Fixes #287

**Pull request merged**
