### PR TITLE
Fix error in DojoAMDRuntimeModule

### LINKED ISSUE #376: Error in DojoAMDRuntimeModule.generate() when used with MonacoEditorWebpackPlugin
First of all, thanks for putting together this plugin! It's been incredibly useful for gradually for moving an old Dojo application into the modern age of NPM/Webpack/etc.

**The Problem**

Using Webpack 5 together with [MonacoEditorWebpackPlugin](https://github.com/microsoft/monaco-editor/tree/main/webpack-plugin) causes some errors to be thrown inside the `generate()` function of `DojoAMDRuntimeModule.js`. This didn't seem to be an issue when using Webpack 4, but this could also be due to behavior changes in the Monaco plugin when they updated to support Webpack 5.

I suspect this is a more general bug, not something that's specific to MonacoEditorWebpackPlugin.

Below is the output from running `webpack --stats-children`:

```
ERROR in webpack/runtime/dojo-webpack-plugin
  Cannot read properties of undefined (reading 'hooks')
  TypeError: Cannot read properties of undefined (reading 'hooks')
      at DojoAMDRuntimeModule.generate (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/dojo-webpack-plugin/lib/DojoAMDRuntimeModule.js:40:24)
      at DojoAMDRuntimeModule.getGeneratedCode (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/RuntimeModule.js:182:44)
      at DojoAMDRuntimeModule.codeGeneration (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/RuntimeModule.js:137:30)
      at /opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:3329:22
      at /opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/Cache.js:93:5
      at Hook.eval [as callAsync] (eval at create (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Cache.get (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/Cache.js:75:18)
      at ItemCacheFacade.get (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/CacheFacade.js:111:15)
      at Compilation._codeGenerationModule (/opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:3322:9)
      at /opt/dev/forks/dpwatrous/dojo-webpack-plugin-sample/node_modules/webpack/lib/Compilation.js:3229:11
```

**Reproduction Steps**

I was able to reproduce this by forking the dojo-webpack-plugin-sample repo and simply adding MonacoEditorWebpackPlugin. Check out [the dpwatrous/bug-repro branch on my fork](https://github.com/dpwatrous/dojo-webpack-plugin-sample/tree/dpwatrous/bug-repro) and run the following to see the error:

```
npm install
npm run build -- --stats-children
```

**Other Info**

It looks like `generate()` is getting called multiple times during the compilation when the Monaco plugin is compiling its bundles. Compilation actually succeeds, but the overall build returns a non-zero exit code and spurious errors.

Here's a screenshot of my debugger the first time `generate()` was called. Note that the "dojo-webpack-plugin" property on `this.compilation` is undefined. This causes `pluginProps` to be undefined, which makes the function error on line 40 when it attempts to access `pluginProps.hooks`.

Screenshot 2023-08-24 at 9 36 36 AM

I was able to fix this issue simply by returning early when `pluginProps` is undefined. Eventually, `generate()` is called again and the function succeeds. I'll put together a PR and link it to this issue, though I'm not confident this is the "right" fix.

### PR DESCRIPTION
**Pull request by dpwatrous**
Fixes #376

### CODE REVIEW

**Comment by dpwatrous** [comment]
I'm not confident this is the best way to fix this issue, but it worked for me.

**Comment by chuckdumont** [comment]
Thanks @dpwatrous, this fix looks fine.

But first I need to figure out why pull request builds are no longer working on this project.

**Comment by dpwatrous** [comment]
Thanks @chuckdumont! FYI I've already patched it locally, so there's no rush as far as I'm concerned. Just figured I'd contribute back the fix.

**Comment by chuckdumont** [comment]
@dpwatrous - please push another commit to your branch to trigger a PR build.  Maybe add a comment to your change like "Not the main compiler so ignore"

**Comment by dpwatrous** [comment]
@chuckdumont sorry for the delay - just saw your last comment! I just reworded my commit messsage and force-pushed. Looks like Travis is running.

**Comment by chuckdumont** [comment]
Fix is available in release 3.0.6

**Pull request merged**
